/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/backend/widget/v2/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          agentId?: string;
        };
        header: {
          'x-bot-token': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | components['schemas']['WidgetConfigDto']
              | components['schemas']['WidgetPreludeDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/contact/create-unverified': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header: {
          'x-bot-token': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateUnverifiedContactDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetContactTokenResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          filters: string;
          offset?: string;
          /**
           * Agents-platform binding: when the widget is bound to an agent, the
           * backend narrows the list to sessions stamped with this agent
           * (`ai_agent_id`). Omitted when the widget isn't agent-bound.
           */
          agentId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaginatedWidgetSessionsDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/session/history/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetHistoryDto'][];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/poll/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSessionAndHistoryDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/create-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWidgetSessionDto'];
        };
      };
      responses: {
        /** @description WidgetSession */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSessionDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/chat/send': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetSendMessageInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSendMessageOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/checkpoint': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetCreateStateCheckpointInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetCreateStateCheckpointOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['FileUploadDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UploadWidgetFileResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/chat/vote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetVoteDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetVoteResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/session/resolve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetResolveSessionInputDto'];
        };
      };
      responses: {
        /** @description WidgetSession */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSessionDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/action/execute': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetActionFormSubmissionInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetActionFormSubmissionOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/submit-csat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetSubmitCsatInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSubmitCsatOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDto: {
      statusCode?: number;
      message?: string;
      error?: string;
    };
    ChatAttachmentDto: {
      id: string;
      name: string;
      size: number;
      type: string;
      url: string;
      openai_file_id?: string;
    };
    FileUploadDto: {
      /**
       * Format: binary
       * @description The file to upload. 5MB max.
       */
      file: string;
    } | null;
    CreateWidgetSessionDto: {
      customData?: {
        [key: string]: string | number | boolean;
      };
      /** Format: uuid */
      agentId?: string;
    } | null;
    WidgetSendMessageInputDto: {
      /** Format: uuid */
      uuid: string;
      content: string;
      session_id: string;
      bot_token: string;
      /** @description Additional headers to be included in the request of action calls */
      headers?: {
        [key: string]: string;
      } | null;
      /** @description Additional query parameters to be included in the query of action calls */
      query_params?: {
        [key: string]: string;
      } | null;
      /** @description Additional body properties to be included in the body of action calls */
      body_properties?: {
        [key: string]: unknown;
      } | null;
      language?: string | null;
      attachments?: components['schemas']['ChatAttachmentDto'][] | null;
      /** @description Context for the AI to be sent with each contact message */
      clientContext?: {
        [key: string]: unknown;
      } | null;
      /** @description Custom data to be sent with each contact message */
      custom_data?: {
        [key: string]: unknown;
      } | null;
      /** @description If there is an active mode, it will be exited and the prompt will be given to the AI for a customized response */
      exit_mode_prompt?: string;
      /** @description A prompt to be given to the AI for a customized response, should be used after an action form is submitted */
      action_form_submitted_prompt?: string;
      initial_messages?: {
        uuid: string;
        content: string;
      }[];
    };
    WidgetCreateStateCheckpointInputDto: {
      session_id: string;
      payload: {
        [key: string]: unknown;
      };
    };
    WidgetVoteDto: {
      /** @enum {string} */
      action: 'upvote' | 'downvote';
      sessionId: string;
      messagePublicId: string;
    };
    WidgetResolveSessionInputDto: {
      session_id: string;
    };
    CreateUnverifiedContactDto: {
      email?: string | null;
      non_verified_name?: string | null;
      non_verified_custom_data?: {
        [key: string]: string | number | boolean;
      } | null;
    };
    WidgetActionFormSubmissionInputDto: {
      sessionId: string;
      formMessageId: string;
      actionId: string;
      request: {
        queryParams?: {
          [key: string]: string;
        };
        pathParams?: {
          [key: string]: string;
        };
        bodyParams?: {
          [key: string]: unknown;
        };
        headers?: {
          [key: string]: string;
        };
      };
    };
    WidgetSubmitCsatInputDto: {
      session_id: string;
      score: number;
      feedback?: string;
      system_message_uuid?: string;
    };
    WidgetVoteResponseDto: {
      messagePublicId: string | null;
      success: boolean;
    };
    WidgetAgentBrandingDto: {
      id: string;
      name: string;
      avatar_url: string | null;
    };
    WidgetConfigDto: {
      org: {
        id: string;
        name: string;
      };
      sessionsPollingIntervalSeconds: number;
      sessionPollingIntervalSeconds: number;
      modes: {
        id: string;
        name: string;
        slug?: string | null;
      }[];
      agent?: components['schemas']['WidgetAgentBrandingDto'];
    };
    WidgetPreludeDto: {
      org: {
        id: string;
        name: string;
      };
      sessionsPollingIntervalSeconds: number;
      sessionPollingIntervalSeconds: number;
      modes: {
        id: string;
        name: string;
        slug?: string | null;
      }[];
      agent?: components['schemas']['WidgetAgentBrandingDto'];
    };
    WidgetContactTokenResponseDto: {
      /** @description The JWT token to use for further requests */
      token: string;
    };
    WidgetCreateStateCheckpointOutputDto: {
      success: boolean;
    };
    /** @enum {string} */
    AssigneeKindEnum: 'human' | 'ai' | 'none';
    /** @enum {string} */
    MessageTypeEnum:
      | 'agent_assigned_by_integration'
      | 'agent_assigned_by_system'
      | 'agent_assigned_by_user'
      | 'agent_changed'
      | 'agent_comment'
      | 'agent_initiated_session'
      | 'agent_joined'
      | 'agent_message'
      | 'agent_reopened_session'
      | 'agent_took_session_from_ai'
      | 'agent_unassigned_by_integration'
      | 'agent_unassigned_by_system'
      | 'agent_unassigned_by_user'
      | 'ai_assumed_the_session_resolved'
      | 'ai_decided_to_not_reply'
      | 'ai_decided_to_resolve_the_issue'
      | 'ai_reopened_session'
      | 'ai_response_cancelled'
      | 'ai_resumed_by_system'
      | 'call_history'
      | 'call_transferred'
      | 'closed_resolved_by_agent'
      | 'closed_resolved_by_api'
      | 'closed_resolved_by_contact'
      | 'closed_resolved_by_integration'
      | 'closed_resolved_by_system'
      | 'closed_unresolved_by_agent'
      | 'closed_unresolved_by_api'
      | 'closed_unresolved_by_system'
      | 'contact_data_updated'
      | 'csat_requested'
      | 'csat_submitted'
      | 'email_draft_message'
      | 'handoff'
      | 'handoff_to_salesforce_miaw'
      | 'handoff_to_zendesk'
      | 'integration_reopened_session'
      | 'message'
      | 'prohibited_topic_detected'
      | 'sequence_message'
      | 'skills_added_by_system'
      | 'sla_applied_by_agent'
      | 'sla_applied_by_system'
      | 'sla_first_reply_breached'
      | 'sla_first_reply_completed_after_breach'
      | 'sla_first_reply_fulfilled'
      | 'sla_first_reply_metric_started'
      | 'sla_freezed_office_hours_ended'
      | 'sla_freezed_snoozed'
      | 'sla_next_reply_breached'
      | 'sla_next_reply_completed_after_breach'
      | 'sla_next_reply_fulfilled'
      | 'sla_next_reply_metric_started'
      | 'sla_removed_by_agent'
      | 'sla_removed_by_system'
      | 'sla_resolution_breached'
      | 'sla_resolution_completed_after_breach'
      | 'sla_resolution_fulfilled'
      | 'sla_resolution_metric_started'
      | 'sla_resolution_paused_resolved'
      | 'sla_resolution_paused_waiting_on_customer'
      | 'sla_resolution_resumed_customer_replied'
      | 'sla_resolution_resumed_reopened'
      | 'sla_resumed_office_hours_started'
      | 'sla_resumed_snooze_cancelled'
      | 'sla_resumed_snooze_expired'
      | 'state_checkpoint'
      | 'sub_status_removed_by_agent'
      | 'sub_status_removed_by_api'
      | 'sub_status_removed_by_integration'
      | 'sub_status_removed_by_system'
      | 'sub_status_set_by_agent'
      | 'sub_status_set_by_api'
      | 'sub_status_set_by_integration'
      | 'sub_status_set_by_system'
      | 'system_reopened_session'
      | 'tag_added_by_agent'
      | 'tag_added_by_api'
      | 'tag_added_by_integration'
      | 'tag_added_by_system'
      | 'tag_removed_by_agent'
      | 'tag_removed_by_api'
      | 'tag_removed_by_integration'
      | 'tag_removed_by_system'
      | 'team_assigned_by_system'
      | 'team_assigned_by_user'
      | 'team_unassigned_by_system'
      | 'team_unassigned_by_user'
      | 'user_confirmed_the_session_resolved'
      | 'workflow_message'
      | 'workflow_note'
      | 'workflow_triggered';
    /** @enum {string} */
    SenderTypeEnum: 'user' | 'agent' | 'ai' | 'system' | 'unknown';
    SystemMessagePayload:
      | (
          | (
              | {
                  /** @constant */
                  type: 'state_checkpoint';
                  payload: {
                    [key: string]: unknown;
                  } | null;
                }
              | {
                  /** @constant */
                  type: 'csat_requested';
                  payload?: null;
                }
            )
          | {
              /** @constant */
              type: 'csat_submitted';
              payload: {
                score?: number | null;
                feedback?: string | null;
              };
            }
        )
      | {
          /** @constant */
          type: 'none';
          payload?: null;
        };
    WidgetHistoryDto: {
      publicId: string;
      type: components['schemas']['MessageTypeEnum'];
      content: {
        text?: string | null;
      };
      sender: {
        kind: components['schemas']['SenderTypeEnum'];
        name?: string | null;
        avatar?: string | null;
      };
      sentAt?: string | null;
      actionCalls?:
        | {
            actionName: string;
            args: unknown;
            result: unknown;
            action: {
              name: string;
              id: string;
              openapi?: {
                openapi_spec_id?: string;
                operation_spec: unknown;
                operation_id?: string;
                operation_method?: string;
              };
              metadata: unknown;
              required_form_submission?: boolean;
              is_handoff_like?: boolean;
            };
          }[]
        | null;
      attachments?: components['schemas']['ChatAttachmentDto'][] | null;
      systemMessagePayload: components['schemas']['SystemMessagePayload'];
      /** @description Agent-v3: activity (reasoning/tool calls) that happened before this message within its turn. */
      stepsBefore?: {
        /** @enum {string} */
        kind: 'reasoning' | 'tool';
        label: string;
      }[];
      /** @description User messages only: display names of page elements the visitor attached with the element picker. */
      pickedElements?: {
        name: string;
      }[];
    };
    WidgetSessionDto: {
      /** Format: uuid */
      id: string;
      ticketNumber: number;
      title: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      isHandedOff: boolean;
      isOpened: boolean;
      assignee: {
        kind: components['schemas']['AssigneeKindEnum'];
        name: string | null;
        avatarUrl: string | null;
      };
      channel: string;
      isVerified: boolean;
      lastMessage: string | null;
      modeId: string | null;
      latestStateCheckpointPayload: {
        [key: string]: unknown;
      } | null;
      sessionAttributes: {
        [key: string]: string | number | boolean;
      };
    };
    PaginatedWidgetSessionsDto: {
      items: components['schemas']['WidgetSessionDto'][];
      next: string | null;
    };
    WidgetSendMessageOutputDto:
      | {
          /** @constant */
          success: true;
          code?:
            | string
            | 'session_assigned_to_human_agent'
            | 'response_cancelled'
            | 'skipping_unuseful_response'
            | 'duplicate_message_ignored'
            | 'ai_response_skipped_by_workflow';
          autopilotResponse?: {
            /** @constant */
            type: 'text';
            value: {
              error: boolean;
              content: string;
            };
            id?: string;
            mightSolveUserIssue: boolean;
            completelyAndFullyCoveredUserIssue: boolean;
            mode?: {
              id: string;
              name: string;
              slug?: string;
            };
            didExitMode?: boolean;
          };
          uiResponse?: {
            /** @constant */
            type: 'ui';
            value: {
              /** @constant */
              type: 'ui_component';
              request_response: unknown;
              name: string;
              content?: string;
            };
            mightSolveUserIssue: boolean;
          };
          formSubmission?: {
            name: string;
            id: string;
            openapi?: {
              openapi_spec_id?: string;
              operation_spec: unknown;
              operation_id?: string;
              operation_method?: string;
            };
            metadata: unknown;
            required_form_submission?: boolean;
            is_handoff_like?: boolean;
          };
          sessionIsHandedOff?: boolean;
          /** @description WidgetSession */
          session?: components['schemas']['WidgetSessionDto'];
        }
      | {
          /** @constant */
          success: false;
          error: {
            code?: string;
            message?: string;
          };
        };
    WidgetSubmitCsatOutputDto: {
      success: boolean;
    };
    WidgetSessionAndHistoryDto: {
      /** @description WidgetSession */
      session: components['schemas']['WidgetSessionDto'];
      history: components['schemas']['WidgetHistoryDto'][];
    };
    WidgetActionFormSubmissionOutputDto: {
      action: {
        response: unknown;
      };
    };
    UploadWidgetFileResponseDto: {
      fileName: string;
      fileUrl: string;
    };
  };
  responses: {
    /** @description Internal Server Error */
    500: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorDto'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
