/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/backend/widget/v2/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header: {
          'x-bot-token': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | components['schemas']['WidgetConfigDto']
              | components['schemas']['WidgetPreludeDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/contact/create-unverified': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header: {
          'x-bot-token': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateUnverifiedContactDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetContactTokenResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          filters: string;
          offset?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaginatedWidgetSessionsDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/session/history/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetHistoryDto'][];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/poll/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSessionAndHistoryDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/create-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWidgetSessionDto'];
        };
      };
      responses: {
        /** @description WidgetSession */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSessionDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/chat/send': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetSendMessageInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSendMessageOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/checkpoint': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetCreateStateCheckpointInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetCreateStateCheckpointOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['FileUploadDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UploadWidgetFileResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/chat/vote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetVoteDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetVoteResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/session/resolve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetResolveSessionInputDto'];
        };
      };
      responses: {
        /** @description WidgetSession */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSessionDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v2/submit-csat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetSubmitCsatInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetSubmitCsatOutputDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/chat/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['WidgetSendMessageInputDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/chat/{sessionId}/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          toolActivity?: 'hidden' | 'status' | 'details';
          reasoning?: 'true' | 'false';
        };
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/chat/{sessionId}/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          toolActivity?: 'hidden' | 'status' | 'details';
          reasoning?: 'true' | 'false';
        };
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetAgentTurnMessagesDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/chat/{sessionId}/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/connections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              server_id: string;
              name: string;
              /** @enum {string} */
              status: 'not_connected' | 'connected' | 'reconnect_required';
            }[];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/connections/{serverId}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          serverId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            request_id?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | {
                  /** Format: uri */
                  authorization_url: string;
                  /** @enum {string} */
                  completion: 'oauth';
                  attempt_id: string;
                }
              | {
                  /** Format: uri */
                  authorization_url: string;
                  /** @enum {string} */
                  completion: 'external';
                };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/connections/{serverId}/attempts/{attemptId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          serverId: string;
          attemptId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status:
                | 'pending'
                | 'connected'
                | 'canceled'
                | 'failed'
                | 'expired';
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/connections/{serverId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          serverId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/backend/widget/v5/dictation/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWidgetDictationSessionDto'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WidgetDictationSessionResponseDto'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDto: {
      statusCode?: number;
      message?: string;
      error?: string;
    };
    ChatAttachmentDto: {
      id: string;
      name: string;
      size: number;
      type: string;
      url: string;
      openai_file_id?: string;
      email_inline?: boolean;
    };
    FileUploadDto: {
      /** Format: binary */
      file: string;
    } | null;
    WidgetPresentationOverrideDto: {
      /** @enum {string} */
      toolActivity?: 'hidden' | 'status' | 'details';
      reasoning?: boolean;
    };
    CreateWidgetSessionDto: {
      customData?: {
        [key: string]: string | number | boolean;
      };
    } | null;
    WidgetSendMessageInputDto: {
      /** Format: uuid */
      uuid: string;
      content: string;
      session_id: string;
      bot_token: string;
      /** @description Additional headers to be included in the request of action calls */
      headers?: {
        [key: string]: string;
      } | null;
      /** @description Additional query parameters to be included in the query of action calls */
      query_params?: {
        [key: string]: string;
      } | null;
      /** @description Additional body properties to be included in the body of action calls */
      body_properties?: {
        [key: string]: unknown;
      } | null;
      language?: string | null;
      attachments?: components['schemas']['ChatAttachmentDto'][] | null;
      /** @description Context for the AI to be sent with each contact message */
      clientContext?: {
        [key: string]: unknown;
      } | null;
      presentation?: components['schemas']['WidgetPresentationOverrideDto'];
      /** @description What the receiving client can render. Set structured_questions to true only when it renders selectable questions from the streaming response. Missing or false disables the structured question tool; this never enables an organization feature. */
      capabilities?: {
        connections?: boolean;
        structured_questions?: boolean;
        rich_replies?: boolean;
        page_effects?: boolean;
      } | null;
      /** @description Per-embed feature narrowing: each flag can only switch OFF a feature the organization enabled for its agent (preamble = progress updates before and during longer tasks; inline_ui = inline rendered components in replies; page_context = the agent sees the page context sent with the message; client_tools = the agent may act on the page). Absent = the organization settings apply. */
      features?: {
        preamble?: boolean;
        inline_ui?: boolean;
        page_context?: boolean;
        client_tools?: boolean;
      } | null;
      /** @description Custom data to be sent with each contact message */
      custom_data?: {
        [key: string]: unknown;
      } | null;
      /** @description If there is an active mode, it will be exited and the prompt will be given to the AI for a customized response */
      exit_mode_prompt?: string;
      /** @description A prompt to be given to the AI for a customized response, should be used after an action form is submitted */
      action_form_submitted_prompt?: string;
      initial_messages?: {
        uuid: string;
        content: string;
      }[];
    };
    WidgetCreateStateCheckpointInputDto: {
      session_id: string;
      payload: {
        [key: string]: unknown;
      };
    };
    WidgetVoteDto: {
      /** @enum {string} */
      action: 'upvote' | 'downvote';
      sessionId: string;
      messagePublicId: string;
    };
    WidgetResolveSessionInputDto: {
      session_id: string;
    };
    CreateUnverifiedContactDto: {
      email?: string | null;
      non_verified_name?: string | null;
      non_verified_custom_data?: {
        [key: string]: string | number | boolean;
      } | null;
    };
    WidgetSubmitCsatInputDto: {
      session_id: string;
      score: number;
      feedback?: string;
      system_message_uuid?: string;
    };
    CreateWidgetDictationSessionDto: {
      language?: string;
    };
    WidgetPresentationDto: {
      /** @default true */
      streaming: boolean;
      /**
       * @default status
       * @enum {string}
       */
      toolActivity: 'hidden' | 'status' | 'details';
      /** @default false */
      reasoning: boolean;
    };
    WidgetVoteResponseDto: {
      messagePublicId: string | null;
      success: boolean;
    };
    /** @enum {string} */
    AssigneeKindEnum: 'human' | 'ai' | 'none';
    /** @enum {string} */
    MessageTypeEnum:
      | 'agent_assigned_by_integration'
      | 'agent_assigned_by_system'
      | 'agent_assigned_by_user'
      | 'agent_changed'
      | 'agent_comment'
      | 'agent_initiated_session'
      | 'agent_joined'
      | 'agent_message'
      | 'agent_reopened_session'
      | 'agent_took_session_from_ai'
      | 'agent_unassigned_by_integration'
      | 'agent_unassigned_by_system'
      | 'agent_unassigned_by_user'
      | 'ai_assumed_the_session_resolved'
      | 'ai_decided_to_not_reply'
      | 'ai_decided_to_resolve_the_issue'
      | 'ai_follow_up_cancelled'
      | 'ai_follow_up_fired'
      | 'ai_follow_up_scheduled'
      | 'ai_reopened_session'
      | 'ai_response_cancelled'
      | 'ai_resumed_by_system'
      | 'ai_suggestion'
      | 'call_history'
      | 'call_transferred'
      | 'closed_resolved_by_agent'
      | 'closed_resolved_by_api'
      | 'closed_resolved_by_contact'
      | 'closed_resolved_by_integration'
      | 'closed_resolved_by_system'
      | 'closed_unresolved_by_agent'
      | 'closed_unresolved_by_api'
      | 'closed_unresolved_by_system'
      | 'contact_data_updated'
      | 'csat_request_cancelled'
      | 'csat_requested'
      | 'csat_submitted'
      | 'email_draft_message'
      | 'handoff'
      | 'handoff_to_salesforce_miaw'
      | 'handoff_to_third_party_failed'
      | 'handoff_to_zendesk'
      | 'integration_reopened_session'
      | 'message'
      | 'pii_attachment_removed'
      | 'prohibited_topic_detected'
      | 'quoted_content_modified'
      | 'salesforce_fields_updated'
      | 'sequence_message'
      | 'session_forwarded'
      | 'session_language_changed_by_agent'
      | 'session_language_changed_by_api'
      | 'session_language_changed_by_integration'
      | 'session_language_changed_by_system'
      | 'skills_added_by_system'
      | 'sla_applied_by_agent'
      | 'sla_applied_by_system'
      | 'sla_first_reply_breached'
      | 'sla_first_reply_completed_after_breach'
      | 'sla_first_reply_fulfilled'
      | 'sla_first_reply_metric_started'
      | 'sla_freezed_office_hours_ended'
      | 'sla_freezed_snoozed'
      | 'sla_next_reply_breached'
      | 'sla_next_reply_completed_after_breach'
      | 'sla_next_reply_fulfilled'
      | 'sla_next_reply_metric_started'
      | 'sla_removed_by_agent'
      | 'sla_removed_by_system'
      | 'sla_resolution_breached'
      | 'sla_resolution_completed_after_breach'
      | 'sla_resolution_fulfilled'
      | 'sla_resolution_metric_started'
      | 'sla_resolution_paused_resolved'
      | 'sla_resolution_paused_waiting_on_customer'
      | 'sla_resolution_resumed_customer_replied'
      | 'sla_resolution_resumed_reopened'
      | 'sla_resumed_office_hours_started'
      | 'sla_resumed_snooze_cancelled'
      | 'sla_resumed_snooze_expired'
      | 'state_checkpoint'
      | 'sub_session_created'
      | 'sub_session_linked_by_agent'
      | 'sub_session_linked_by_api'
      | 'sub_session_linked_by_integration'
      | 'sub_session_linked_by_system'
      | 'sub_session_unlinked_by_agent'
      | 'sub_session_unlinked_by_api'
      | 'sub_session_unlinked_by_integration'
      | 'sub_session_unlinked_by_system'
      | 'sub_status_removed_by_agent'
      | 'sub_status_removed_by_api'
      | 'sub_status_removed_by_integration'
      | 'sub_status_removed_by_system'
      | 'sub_status_set_by_agent'
      | 'sub_status_set_by_api'
      | 'sub_status_set_by_integration'
      | 'sub_status_set_by_system'
      | 'system_reopened_session'
      | 'tag_added_by_agent'
      | 'tag_added_by_api'
      | 'tag_added_by_integration'
      | 'tag_added_by_system'
      | 'tag_removed_by_agent'
      | 'tag_removed_by_api'
      | 'tag_removed_by_integration'
      | 'tag_removed_by_system'
      | 'team_assigned_by_integration'
      | 'team_assigned_by_system'
      | 'team_assigned_by_user'
      | 'team_unassigned_by_integration'
      | 'team_unassigned_by_system'
      | 'team_unassigned_by_user'
      | 'user_confirmed_the_session_resolved'
      | 'workflow_message'
      | 'workflow_note'
      | 'workflow_triggered';
    /** @enum {string} */
    SenderTypeEnum: 'user' | 'agent' | 'ai' | 'system' | 'unknown';
    SystemMessagePayload:
      | (
          | (
              | {
                  /** @constant */
                  type: 'state_checkpoint';
                  payload: {
                    [key: string]: unknown;
                  } | null;
                }
              | {
                  /** @constant */
                  type: 'csat_requested';
                  payload?: null;
                }
            )
          | {
              /** @constant */
              type: 'csat_submitted';
              payload: {
                score?: number | null;
                feedback?: string | null;
              };
            }
        )
      | {
          /** @constant */
          type: 'none';
          payload?: null;
        };
    WidgetSessionDto: {
      /** Format: uuid */
      id: string;
      ticketNumber: number;
      title: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      isHandedOff: boolean;
      isOpened: boolean;
      assignee: {
        kind: components['schemas']['AssigneeKindEnum'];
        name: string | null;
        avatarUrl: string | null;
      };
      channel: string;
      isVerified: boolean;
      lastMessage: string | null;
      modeId: string | null;
      latestStateCheckpointPayload: {
        [key: string]: unknown;
      } | null;
      sessionAttributes: {
        [key: string]: string | number | boolean;
      };
      customStatus: {
        /** Format: uuid */
        id: string;
        name: string;
        description: string | null;
        color: string | null;
        icon: string | null;
      } | null;
    };
    PaginatedWidgetSessionsDto: {
      items: components['schemas']['WidgetSessionDto'][];
      next: string | null;
    };
    WidgetAgentFeaturesDto: {
      preamble: boolean;
      inline_ui: boolean;
      dictation: boolean;
      attachments: boolean;
      page_context: boolean;
      client_tools: boolean;
    };
    WidgetAgentDto: {
      name: string;
      avatar_url: string | null;
      streaming: boolean;
      presentation?: components['schemas']['WidgetPresentationDto'];
      features: components['schemas']['WidgetAgentFeaturesDto'];
    };
    WidgetConfigDto: {
      org: {
        id: string;
        name: string;
      };
      sessionsPollingIntervalSeconds: number;
      sessionPollingIntervalSeconds: number;
      modes: {
        id: string;
        name: string;
        slug?: string | null;
      }[];
      agent: components['schemas']['WidgetAgentDto'];
    };
    WidgetPreludeDto: {
      org: {
        id: string;
        name: string;
      };
      sessionsPollingIntervalSeconds: number;
      sessionPollingIntervalSeconds: number;
      modes: {
        id: string;
        name: string;
        slug?: string | null;
      }[];
      agent: components['schemas']['WidgetAgentDto'];
    };
    WidgetHistoryDto: {
      publicId: string;
      type: components['schemas']['MessageTypeEnum'];
      content: {
        text?: string | null;
      };
      sender: {
        kind: components['schemas']['SenderTypeEnum'];
        name?: string | null;
        avatar?: string | null;
      };
      sentAt?: string | null;
      actionCalls?:
        | {
            actionName: string;
            args: unknown;
            result: unknown;
            action: {
              name: string;
              id: string;
              openapi?: {
                openapi_spec_id?: string;
                operation_spec: unknown;
                operation_id?: string;
                operation_method?: string;
              };
              metadata: unknown;
              required_form_submission?: boolean;
              is_handoff_like?: boolean;
            };
          }[]
        | null;
      attachments?: components['schemas']['ChatAttachmentDto'][] | null;
      systemMessagePayload: components['schemas']['SystemMessagePayload'];
      pickedElements?: {
        name: string;
        note?: string;
        snapshotUrl?: string;
      }[];
    };
    WidgetSessionAndHistoryDto: {
      /** @description WidgetSession */
      session: components['schemas']['WidgetSessionDto'];
      history: components['schemas']['WidgetHistoryDto'][];
    };
    WidgetSendMessageOutputDto:
      | {
          /** @constant */
          success: true;
          code?:
            | string
            | 'session_assigned_to_human_agent'
            | 'response_cancelled'
            | 'skipping_unuseful_response'
            | 'duplicate_message_ignored'
            | 'ai_response_skipped_by_workflow'
            | 'ai_skipped_spam'
            | 'steered_into_live_turn'
            | 'session_busy';
          autopilotResponse?: {
            /** @constant */
            type: 'text';
            value: {
              error: boolean;
              content: string;
            };
            id?: string;
            mightSolveUserIssue: boolean;
            completelyAndFullyCoveredUserIssue: boolean;
            assistMode: boolean;
            mode?: {
              id: string;
              name: string;
              slug?: string;
            };
            didExitMode?: boolean;
          };
          uiResponse?: {
            /** @constant */
            type: 'ui';
            value: {
              /** @constant */
              type: 'ui_component';
              request_response: unknown;
              name: string;
              content?: string;
            };
            mightSolveUserIssue: boolean;
          };
          formSubmission?: {
            name: string;
            id: string;
            openapi?: {
              openapi_spec_id?: string;
              operation_spec: unknown;
              operation_id?: string;
              operation_method?: string;
            };
            metadata: unknown;
            required_form_submission?: boolean;
            is_handoff_like?: boolean;
          };
          sessionIsHandedOff?: boolean;
          /** @description WidgetSession */
          session?: components['schemas']['WidgetSessionDto'];
        }
      | {
          /** @constant */
          success: false;
          error: {
            code?: string;
            message?: string;
          };
        };
    WidgetCreateStateCheckpointOutputDto: {
      success: boolean;
    };
    WidgetSubmitCsatOutputDto: {
      success: boolean;
      /**
       * @description Why the submit was refused. rescore_locked = the org rescore window has closed, so the recorded score can no longer be changed by the customer. request_cancelled = the survey was voided before it was answered, so a rating is no longer accepted at all
       * @enum {string}
       */
      reason?: 'rescore_locked' | 'request_cancelled';
    };
    WidgetContactTokenResponseDto: {
      /** @description The JWT token to use for further requests */
      token: string;
    };
    UploadWidgetFileResponseDto: {
      fileName: string;
      fileUrl: string;
    };
    WidgetAgentTurnMessagesDto: {
      handled_connection_request_ids: string[];
      turns: {
        /** Format: uuid */
        turn_id: string;
        ui_parts:
          | ({
              type: string;
            } & {
              [key: string]: unknown;
            })[]
          | null;
        message_uuids: string[];
      }[];
    };
    WidgetDictationSessionResponseDto: {
      token: string;
      expiresAt: string;
      model: string;
    };
  };
  responses: {
    /** @description Internal Server Error */
    500: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorDto'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
